title: "Barad Lab"
description: "The Barad Lab is a cryo-electron tomography and computational structural biology lab at Oregon Health & Science University"
cdn: https://cdn.baradlab.com/file/baradlabweb/
url: https://baradlab.com
baseurl: /

paginate: 5
plugins: [jekyll-paginate]
paginate_path: "news/page:num"

permalink: pretty
markdown: kramdown
kramdown:
  parse_block_html: true


  
collections:
  members: 
    output: True
  alumni:
    output: False
  publications:
    group: publications
    layout: default
    output: True


